server:
  port: 10010
spring:
  application:
    name: leyou-gateway

eureka:
  client:
    registry-fetch-interval-seconds: 5  #拉取服务的间隔时间
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api  #路由路径前缀，统一公共登录前缀,页面上所有请求都会以api为开头,因为前端配置了所有服务请求开头都为api
  routes:
    item-service: /item/** #路由到商品的微服务